### ISSUE TITLE
请问能具体告知一下怎么挂载到localhost：8000

### ISSUE THREAD

**Issue by jianye0428** [Roger-luo/Brochure.jl#9]
你好
按照提示我运行了`using Documenter``using LiveServer``include(“make.jl”)``serve()`
但是没有在localhost：8000看到具体教程。
请问，具体应该怎么做呢？

谢谢

Jian

**Comment by Roger-luo** [comment]
sorry，不是serve是 `serve_book`

**Comment by Roger-luo** [comment]
已修复，现在只需要 `include("make.jl")` 或者 `julia make.jl serve` 即可
